# ===========================================================================
#
#                            PUBLIC DOMAIN NOTICE
#               National Center for Biotechnology Information
#
#  This software/database is a "United States Government Work" under the
#  terms of the United States Copyright Act.  It was written as part of
#  the author's official duties as a United States Government employee and
#  thus cannot be copyrighted.  This software/database is freely available
#  to the public for use. The National Library of Medicine and the U.S.
#  Government have not placed any restriction on its use or reproduction.
#
#  Although all reasonable efforts have been taken to ensure the accuracy
#  and reliability of the software and data, the NLM and the U.S.
#  Government do not and cannot warrant the performance or results that
#  may be obtained by using this software or data. The NLM and the U.S.
#  Government disclaim all warranties, express or implied, including
#  warranties of performance, merchantability or fitness for any particular
#  purpose.
#
#  Please cite the author in any work or product based on this material.
#
# ===========================================================================

default: std

TOP ?= $(abspath ..)
MODULE = java

include $(TOP)/build/Makefile.env

#-------------------------------------------------------------------------------
# outer targets
#
all std:
	@ $(MAKE) BUILD=$(BUILD) TOOLSET=$(TOOLSET) COMP=$(COMP) LNKG=$(LNKG) \
      TOP=$(TOP) SRCDIR=$(SRCDIR) OUTDIR=$(OUTDIR) -C $(SRCDIR)           \
      -f $(SRCDIR)/Makefile javadoc

.PHONY: all std

#-------------------------------------------------------------------------------
# clean
#
clean:
	rm `find $(SRCDIR) -name "*.html"`

.PHONY: clean

#-------------------------------------------------------------------------------
# javadoc
#
javadoc:
	mv gov/nih/nlm/ncbi/ngs/TestyTheBear.java gov/nih/nlm/ncbi/ngs/TestyTheBear.xjava
	javadoc -notimestamp -tag .note:a:"NOTE:" \
	-classpath $(CLSPATH) -sourcepath . gov.nih.nlm.ncbi.ngs ngs
	mv gov/nih/nlm/ncbi/ngs/TestyTheBear.xjava gov/nih/nlm/ncbi/ngs/TestyTheBear.java

.PHONY: javadoc
