
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* %endif */

/* %if-not-reentrant */
/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE schema_yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE schema_yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via schema_yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

void schema_yyrestart (FILE *input_file ,yyscan_t yyscanner );
void schema_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE schema_yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void schema_yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void schema_yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void schema_yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void schema_yypop_buffer_state (yyscan_t yyscanner );

static void schema_yyensure_buffer_stack (yyscan_t yyscanner );
static void schema_yy_load_buffer_state (yyscan_t yyscanner );
static void schema_yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER schema_yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE schema_yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE schema_yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE schema_yy_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

/* %endif */

void *schema_yyalloc (yy_size_t ,yyscan_t yyscanner );
void *schema_yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void schema_yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer schema_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        schema_yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            schema_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        schema_yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            schema_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define schema_yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	yyg->yy_c_buf_p = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[303] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   94,   92,
       91,   91,   35,    9,    2,   31,    7,    8,   12,   19,
        3,   20,   18,   13,   24,   23,   14,    1,   10,    6,
       11,   21,   78,   15,   16,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,    4,
       17,    5,   85,   85,   87,   92,   85,   92,   92,   73,
       71,   35,   34,    0,    0,   83,   31,    0,   30,    0,
        0,   29,   80,   84,   90,   28,   24,    0,    0,   23,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,

       78,   78,   78,   78,   78,   78,   85,   86,   87,    0,
       88,   85,    0,   89,    0,   73,    0,    0,   73,   34,
       37,    0,   30,   33,   22,    0,   80,   90,   28,    0,
       79,   25,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   85,   72,   70,   70,   70,   36,
        0,   82,    0,   32,   27,   26,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   56,   78,   78,   78,   78,   78,

       78,   64,   65,   78,   78,   74,   78,   76,   78,    0,
       78,   78,   78,   41,   78,   43,   78,   78,   78,   78,
       78,   78,   50,   78,   78,   78,   54,   78,   78,   78,
       78,   78,   61,   78,   78,   78,   78,   78,   78,   78,
       77,   81,   78,   78,   78,   42,   78,   78,   46,   78,
       48,   49,   51,   78,   78,   78,   78,   58,   59,   60,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       44,   78,   47,   78,   53,   78,   78,   78,   63,   66,
       67,   78,   69,   75,   78,   78,   78,   45,   52,   55,
       57,   62,   68,   78,   78,   40,   78,   78,   38,   78,

       39,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    1,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,   25,   26,   26,   26,   26,   27,   26,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   29,   28,   28,
       30,   31,   32,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   28,   28,   43,   44,   45,
       46,   47,   28,   48,   49,   50,   51,   52,   53,   54,
       55,   28,   56,   57,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        4,    1,    1,    1,    5,    1,    6,    6,    6,    1,
        1,    1,    1,    1,    1,    6,    6,    6,    6,    1,
        1,    1,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    6,    1
    } ;

static yyconst flex_uint16_t yy_base[319] =
    {   0,
        0,    0,   57,   60,   63,   78,   81,   88,  511,  512,
      512,  512,   65,   69,  512,   70,  512,  512,  512,  512,
      512,  512,   93,   98,   98,  103,  512,  512,  512,  512,
      512,  512,    0,  512,  512,  477,  466,  462,   85,   48,
       90,  462,  464,  464,  466,   89,   92,  104,  455,  512,
        0,  512,    0,    0,  512,  132,  117,  133,  121,  139,
      144,  146,  512,  161,    0,  154,  159,  171,  512,    0,
      487,  166,    0,  512,    0,  169,  180,    0,  210,  191,
        0,  131,  459,   86,  450,  142,  463,  448,  454,  446,
      450,  458,  449,  437,  155,  450,  456,  454,  444,  149,

      440,  443,  437,  163,  442,  441,    0,  209,  512,  219,
      512,  471,  239,  512,  196,  239,  464,  199,  244,  512,
      234,  214,  512,  262,  512,  234,    0,    0,  254,  257,
        0,    0,  434,  433,  433,  443,  425,  228,  441,  428,
      439,  426,  433,  421,  432,  432,  424,  424,  416,  427,
      412,  424,  411,  417,  412,  418,  419,  418,  413,  405,
      400,  402,  414,  400,  438,  265,  512,  268,  279,  512,
      286,  284,  297,  512,  290,  295,  415,  394,  396,  396,
      400,  393,  394,  406,  403,  388,  401,  389,  398,  397,
      384,  382,  382,  389,  384,  381,  384,  385,  388,  382,

      384,    0,  231,  386,  380,    0,  370,    0,  382,  301,
      378,  385,  362,    0,  371,    0,  369,  380,  375,  369,
      373,  365,    0,  370,  366,  370,    0,  370,  360,  359,
      369,  366,    0,  367,  362,  361,  356,  354,  336,  342,
        0,  304,  332,  317,  311,    0,  306,  299,    0,  293,
        0,    0,    0,  296,  289,  292,  282,    0,    0,    0,
      274,  268,  276,  260,  255,  259,  248,  256,  250,  241,
        0,  226,    0,  215,    0,  200,  185,  196,    0,    0,
        0,  186,    0,    0,  184,  174,  166,    0,    0,    0,
        0,    0,    0,  156,  128,    0,  112,   95,    0,   62,

        0,  512,  328,  334,  340,  346,  348,  350,   89,  356,
      362,  368,  374,  380,   69,  386,   63,  392
    } ;

static yyconst flex_int16_t yy_def[319] =
    {   0,
      302,    1,  303,  303,  303,  303,  304,  304,  302,  302,
      302,  302,  305,  302,  302,  306,  302,  302,  302,  302,
      302,  302,  307,  302,  308,  308,  302,  302,  302,  302,
      302,  302,  309,  302,  302,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  302,
      309,  302,  310,  310,  302,  311,  310,  311,  302,  302,
      312,  305,  302,  305,  313,  302,  306,  306,  302,  314,
      302,  302,  315,  302,  316,  302,  302,  317,  317,  302,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  310,  311,  302,  311,
      302,  318,  311,  302,  302,  302,  302,  302,  302,  302,
      313,  302,  302,  314,  302,  302,  315,  316,  302,  302,
      317,   79,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  318,  302,  302,  302,  302,  302,
      313,  302,  314,  302,  302,  302,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  302,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  302,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,    0,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302
    } ;

static yyconst flex_uint16_t yy_nxt[571] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   26,   27,
       28,   29,   30,   31,   32,   33,   33,   33,   33,   34,
       10,   35,   36,   37,   33,   38,   39,   40,   41,   33,
       33,   42,   43,   33,   33,   33,   44,   45,   46,   47,
       33,   48,   49,   33,   33,   50,   51,   52,   54,   55,
       54,   54,   55,   54,   54,   55,   54,   56,  131,   63,
       56,   64,   57,   58,  127,   57,   68,   69,   57,   54,
       55,   54,   11,   12,   11,   66,   66,   66,   58,   11,
       12,   11,   87,   57,   81,   65,   59,   60,   61,   60,

       70,   88,  301,   59,   60,   61,   60,   71,   74,   72,
       72,   72,   76,   75,   77,   77,   77,   76,   85,   80,
       80,   80,   86,   89,   96,   98,   79,   74,  137,   99,
      138,   74,  112,   90,  109,  109,   75,  102,   97,  100,
       91,  103,  110,  113,  300,  104,  101,  111,  114,  105,
      120,   79,   64,  115,   79,  116,  116,  116,  118,  299,
      119,  119,  119,   62,   62,   68,  123,  298,  122,  302,
       66,   66,   66,   67,   67,  133,   65,  140,  134,  302,
      141,  135,   72,   72,   72,  129,  129,  129,  150,   70,
      156,  302,  126,  297,   76,  130,   77,   77,   77,  157,

      161,  302,  296,  126,  151,   76,  130,   80,   80,   80,
      162,  302,  166,  166,  166,  168,  166,  166,  295,  302,
      294,  109,  126,  293,  302,  130,  132,  132,  132,  110,
      172,  172,  172,  292,  111,  132,  132,  302,  170,  291,
      171,  109,  290,  132,  132,  132,  132,  132,  132,  113,
      175,  175,  175,  115,  114,  116,  116,  116,  115,  289,
      169,  116,  116,  288,   65,  302,  132,  236,  173,  174,
      129,  129,  129,  176,  176,  176,  182,  183,  287,  237,
      130,  166,  166,  166,  166,  166,  166,  286,  121,  285,
      284,  130,   70,  115,  302,  116,  116,  116,  210,  124,

      172,  172,  172,  283,  282,  302,  175,  175,  175,  281,
      130,  176,  176,  176,  280,  279,  302,  242,  242,  242,
      242,  242,  242,  278,  277,  276,  275,  302,   53,   53,
       53,   53,   53,   53,   10,   10,   10,   10,   10,   10,
       62,  274,  273,   62,   62,   62,   67,  272,  271,   67,
       67,   67,   73,   73,   78,   78,  107,  270,  107,  269,
      107,  107,  108,  108,  108,  108,  108,  108,  117,  268,
      117,  117,  117,  117,  121,  267,  121,  121,  121,  121,
      124,  266,  124,  124,  124,  124,  128,  265,  128,  128,
      128,  128,  165,  264,  165,  165,  165,  165,  263,  262,

      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  241,
      240,  239,  238,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  128,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  181,  180,  179,  178,  177,
      167,  128,  164,  163,  160,  159,  158,  155,  154,  153,
      152,  149,  148,  147,  146,  145,  144,  143,  142,  139,

      136,  125,  106,   95,   94,   93,   92,   84,   83,   82,
      302,    9,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302
    } ;

static yyconst flex_int16_t yy_chk[571] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    4,    4,    4,    5,    5,    5,    3,  317,   13,
        4,   13,    3,    5,  315,    4,   16,   16,    5,    6,
        6,    6,    7,    7,    7,   14,   14,   14,    6,    8,
        8,    8,   40,    6,  309,   13,    7,    7,    7,    7,

       16,   40,  300,    8,    8,    8,    8,   23,   24,   23,
       23,   23,   25,   24,   25,   25,   25,   26,   39,   26,
       26,   26,   39,   41,   46,   47,   25,   57,   84,   47,
       84,   59,   57,   41,   56,   58,   59,   48,   46,   47,
       41,   48,   56,   58,  298,   48,   47,   56,   58,   48,
       62,   25,   62,   60,   25,   60,   60,   60,   61,  297,
       61,   61,   61,   64,   64,   67,   67,  295,   66,   64,
       66,   66,   66,   68,   68,   82,   62,   86,   82,   68,
       86,   82,   72,   72,   72,   76,   76,   76,   95,   67,
      100,   64,   72,  294,   77,   76,   77,   77,   77,  100,

      104,   68,  287,   72,   95,   80,   76,   80,   80,   80,
      104,  108,  115,  115,  115,  118,  118,  118,  286,  108,
      285,  110,   72,  282,  108,   76,   79,   79,   79,  110,
      122,  122,  122,  278,  110,   79,   79,  121,  121,  277,
      121,  113,  276,   79,   79,   79,   79,   79,   79,  113,
      126,  126,  126,  116,  113,  116,  116,  116,  119,  274,
      119,  119,  119,  272,  121,  124,   79,  203,  124,  124,
      129,  129,  129,  130,  130,  130,  138,  138,  270,  203,
      129,  166,  166,  166,  168,  168,  168,  269,  171,  268,
      267,  129,  124,  169,  171,  169,  169,  169,  172,  173,

      172,  172,  172,  266,  265,  173,  175,  175,  175,  264,
      129,  176,  176,  176,  263,  262,  171,  210,  210,  210,
      242,  242,  242,  261,  257,  256,  255,  173,  303,  303,
      303,  303,  303,  303,  304,  304,  304,  304,  304,  304,
      305,  254,  250,  305,  305,  305,  306,  248,  247,  306,
      306,  306,  307,  307,  308,  308,  310,  245,  310,  244,
      310,  310,  311,  311,  311,  311,  311,  311,  312,  243,
      312,  312,  312,  312,  313,  240,  313,  313,  313,  313,
      314,  239,  314,  314,  314,  314,  316,  238,  316,  316,
      316,  316,  318,  237,  318,  318,  318,  318,  236,  235,

      234,  232,  231,  230,  229,  228,  226,  225,  224,  222,
      221,  220,  219,  218,  217,  215,  213,  212,  211,  209,
      207,  205,  204,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  137,  136,  135,  134,  133,
      117,  112,  106,  105,  103,  102,  101,   99,   98,   97,
       96,   94,   93,   92,   91,   90,   89,   88,   87,   85,

       83,   71,   49,   45,   44,   43,   42,   38,   37,   36,
        9,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[94] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,     };

static yyconst flex_int16_t yy_rule_linenum[93] =
    {   0,
       83,   84,   85,   86,   87,   88,   89,   90,   91,   92,
       93,   94,   95,   96,   97,   98,   99,  100,  101,  102,
      103,  105,  107,  108,  109,  110,  111,  112,  113,  116,
      117,  118,  119,  122,  123,  124,  125,  128,  129,  130,
      131,  132,  133,  134,  135,  136,  137,  138,  139,  140,
      141,  142,  143,  144,  145,  146,  147,  148,  149,  150,
      151,  152,  153,  154,  155,  156,  157,  158,  160,  161,
      162,  163,  164,  166,  167,  168,  169,  171,  172,  173,
      175,  176,  177,  180,  181,  182,  183,  184,  185,  188,
      191,  194

    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
/*===========================================================================
*
*                            PUBLIC DOMAIN NOTICE
*               National Center for Biotechnology Information
*
*  This software/database is a "United States Government Work" under the
*  terms of the United States Copyright Act.  It was written as part of
*  the author's official duties as a United States Government employee and
*  thus cannot be copyrighted.  This software/database is freely available
*  to the public for use. The National Library of Medicine and the U.S.
*  Government have not placed any restriction on its use or reproduction.
*
*  Although all reasonable efforts have been taken to ensure the accuracy
*  and reliability of the software and data, the NLM and the U.S.
*  Government do not and cannot warrant the performance or results that
*  may be obtained by using this software or data. The NLM and the U.S.
*  Government disclaim all warranties, express or implied, including
*  warranties of performance, merchantability or fitness for any particular
*  purpose.
*
*  Please cite the author in any work or product based on this material.
*
* ===========================================================================
*
*/
#line 28 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"

#define YYDEBUG 1

#include "schema-lex.h"

typedef struct ParseTree ParseTree; /* a fake declaration to make the scanner compile */
#include "schema-tokens.h"

#define YY_USER_ACTION \
    yylloc->first_line = yylloc->last_line; \
    yylloc->first_column = yylloc->last_column; \
    for(int i = 0; yytext[i] != '\0'; i++) { \
        if(yytext[i] == '\n') { \
            yylloc->last_line++; \
            yylloc->last_column = 1; \
        } \
        else { \
            yylloc->last_column++; \
        } \
    }

static void AddWhitespace ( SchemaScanBlock* p_sb, const char* p_ws, size_t p_length );

#define AddWs() AddWhitespace ( ( SchemaScanBlock * ) yyextra, yytext, yyleng )

#define YY_NO_UNISTD_H 1
/* re-entrant scanner */
/* maintain state stack */
/* let parser handle EOF */
/* start-state for slash-star comments */



#line 861 "<stdout>"

#define INITIAL 0
#define CMT_SLASH_STAR 1
#define CMT_MULTI_LINE 2
#define VERSION_STATE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

/* %if-c-only */

static int yy_init_globals (yyscan_t yyscanner );

/* %endif */

/* %if-reentrant */

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int schema_yylex_init (yyscan_t* scanner);

int schema_yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* %endif */

/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int schema_yylex_destroy (yyscan_t yyscanner );

int schema_yyget_debug (yyscan_t yyscanner );

void schema_yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE schema_yyget_extra (yyscan_t yyscanner );

void schema_yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *schema_yyget_in (yyscan_t yyscanner );

void schema_yyset_in  (FILE * _in_str ,yyscan_t yyscanner );

FILE *schema_yyget_out (yyscan_t yyscanner );

void schema_yyset_out  (FILE * _out_str ,yyscan_t yyscanner );

yy_size_t schema_yyget_leng (yyscan_t yyscanner );

char *schema_yyget_text (yyscan_t yyscanner );

int schema_yyget_lineno (yyscan_t yyscanner );

void schema_yyset_lineno (int _line_number ,yyscan_t yyscanner );

int schema_yyget_column  (yyscan_t yyscanner );

void schema_yyset_column (int _column_no ,yyscan_t yyscanner );

/* %if-bison-bridge */

YYSTYPE * schema_yyget_lval (yyscan_t yyscanner );

void schema_yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *schema_yyget_lloc (yyscan_t yyscanner );
    
        void schema_yyset_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int schema_yywrap (yyscan_t yyscanner );
#else
extern int schema_yywrap (yyscan_t yyscanner );
#endif
#endif

/* %not-for-header */

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

    static void yy_push_state (int _new_state ,yyscan_t yyscanner);
    
    static void yy_pop_state (yyscan_t yyscanner );
    
    static int yy_top_state (yyscan_t yyscanner );
    
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int schema_yylex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int schema_yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			schema_yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				schema_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		schema_yy_load_buffer_state(yyscanner );
		}

	{
/* %% [7.0] user's declarations go here */
#line 79 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"


 /* literals */

#line 1232 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 303 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 302 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 93 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 93 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 94 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 83 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 84 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 85 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 86 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 87 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 88 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 89 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 90 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 91 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 92 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 93 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 94 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 95 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 96 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 97 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 98 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 99 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 100 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 101 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 102 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 103 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return yytext [ 0 ]; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 105 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return ELLIPSIS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 107 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return DECIMAL; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 108 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return OCTAL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 109 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return HEX; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 110 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return EXP_FLOAT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 111 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return EXP_FLOAT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 112 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return FLOAT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 113 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return FLOAT; }
	YY_BREAK
/* single quoted strings */
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 116 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return STRING; }
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 117 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return STRING; } /*TODO: handle unterminated */
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 118 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return ESCAPED_STRING; }
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 119 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return ESCAPED_STRING; }  /*TODO: handle unterminated */
	YY_BREAK
/* double quoted strings */
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 122 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return STRING; }
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 123 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return STRING; } /*TODO: handle unterminated */
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 124 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return ESCAPED_STRING; }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 125 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return ESCAPED_STRING; }  /*TODO: handle unterminated */
	YY_BREAK
/* keywords */
case 38:
YY_RULE_SETUP
#line 128 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW___no_header; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 129 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW___row_length; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 130 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW___untyped; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 131 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_alias; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 132 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_column; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 133 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_const; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 134 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_control; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 135 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_database; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 136 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_decode; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 137 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_default; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 138 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_encode; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 139 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_extern; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 140 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_false; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 141 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_fmtdef; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 142 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_function; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 143 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_include; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 144 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_limit; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 145 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_physical; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 146 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_read; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 147 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_readonly; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 148 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_return; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 149 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_schema; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 150 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_static; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 151 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_table; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 152 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_template; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 153 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_trigger; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 154 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_true; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 155 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_type; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 156 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_typedef; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 157 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_typeset; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 158 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_validate; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 160 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ yy_push_state ( VERSION_STATE, yyscanner ); return KW_version; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 161 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ yy_pop_state ( yyscanner ); return VERS_1_0; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 162 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ yy_pop_state ( yyscanner ); return VERS_1_0; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 163 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ yy_pop_state ( yyscanner ); return FLOAT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 164 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ yy_pop_state ( yyscanner ); return DECIMAL; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 166 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_view; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 167 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_virtual; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 168 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_void; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 169 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return KW_write; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 171 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return IDENTIFIER_1_0; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 172 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return IDENTIFIER_1_0; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 173 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return PHYSICAL_IDENTIFIER_1_0; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 175 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return VERSION; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 176 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return VERSION; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 177 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return VERSION; }
	YY_BREAK
/* multi-line comments */
case 84:
YY_RULE_SETUP
#line 180 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ yy_push_state ( CMT_SLASH_STAR, yyscanner ); AddWs(); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 181 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ AddWs(); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 182 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ AddWs(); }
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 183 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ BEGIN CMT_MULTI_LINE; AddWs(); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 184 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ yy_pop_state ( yyscanner ); AddWs(); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 185 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ yy_pop_state ( yyscanner ); AddWs(); }
	YY_BREAK
/* line comments */
case 90:
YY_RULE_SETUP
#line 188 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ AddWs(); }
	YY_BREAK
/* ignored tokens */
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 191 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ AddWs(); }
	YY_BREAK
/* unrecognized input */
case 92:
YY_RULE_SETUP
#line 194 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
{ return UNRECOGNIZED; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 196 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"
ECHO;
	YY_BREAK
#line 1802 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CMT_SLASH_STAR):
case YY_STATE_EOF(CMT_MULTI_LINE):
case YY_STATE_EOF(VERSION_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * schema_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( schema_yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of schema_yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	yy_size_t number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					schema_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			schema_yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) schema_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 303 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
/* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 303 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 302);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

    if ( c == '\n' ){
        --yylineno;
    }

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					schema_yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( schema_yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

/* %% [19.0] update BOL and yylineno */
	if ( c == '\n' )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void schema_yyrestart  (FILE * input_file , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        schema_yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            schema_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	schema_yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	schema_yy_load_buffer_state(yyscanner );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
/* %if-c-only */
    void schema_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		schema_yypop_buffer_state();
	 *		schema_yypush_buffer_state(new_buffer);
     */
	schema_yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	schema_yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (schema_yywrap()) processing, but the only time this flag
	 * is looked at is after schema_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/* %if-c-only */
static void schema_yy_load_buffer_state  (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE schema_yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) schema_yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in schema_yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) schema_yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in schema_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	schema_yy_init_buffer(b,file ,yyscanner);

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with schema_yy_create_buffer()
 * @param yyscanner The scanner object.
 */
/* %if-c-only */
    void schema_yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		schema_yyfree((void *) b->yy_ch_buf ,yyscanner );

	schema_yyfree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a schema_yyrestart() or at EOF.
 */
/* %if-c-only */
    static void schema_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	schema_yy_flush_buffer(b ,yyscanner);

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then schema_yy_init_buffer was _probably_
     * called from schema_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
/* %if-c-only */
    void schema_yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		schema_yy_load_buffer_state(yyscanner );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
/* %if-c-only */
void schema_yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	schema_yyensure_buffer_stack(yyscanner);

	/* This block is copied from schema_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from schema_yy_switch_to_buffer. */
	schema_yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
/* %if-c-only */
void schema_yypop_buffer_state (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	schema_yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		schema_yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void schema_yyensure_buffer_stack (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)schema_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in schema_yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)schema_yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in schema_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE schema_yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) schema_yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in schema_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	schema_yy_switch_to_buffer(b ,yyscanner );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to schema_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       schema_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE schema_yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return schema_yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to schema_yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE schema_yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) schema_yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in schema_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = schema_yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in schema_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

/* %if-c-only */
    static void yy_push_state (int  _new_state , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( yyg->yy_start_stack_ptr >= yyg->yy_start_stack_depth )
		{
		yy_size_t new_size;

		yyg->yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yyg->yy_start_stack_depth * sizeof( int );

		if ( ! yyg->yy_start_stack )
			yyg->yy_start_stack = (int *) schema_yyalloc(new_size ,yyscanner );

		else
			yyg->yy_start_stack = (int *) schema_yyrealloc((void *) yyg->yy_start_stack,new_size ,yyscanner );

		if ( ! yyg->yy_start_stack )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	yyg->yy_start_stack[yyg->yy_start_stack_ptr++] = YY_START;

	BEGIN(_new_state);
}

/* %if-c-only */
    static void yy_pop_state  (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( --yyg->yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yyg->yy_start_stack[yyg->yy_start_stack_ptr]);
}

/* %if-c-only */
    static int yy_top_state  (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	return yyg->yy_start_stack[yyg->yy_start_stack_ptr - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE schema_yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/* %endif */

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int schema_yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int schema_yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *schema_yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *schema_yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t schema_yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *schema_yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/* %if-reentrant */

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void schema_yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void schema_yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "schema_yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void schema_yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "schema_yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see schema_yy_switch_to_buffer
 */
void schema_yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void schema_yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int schema_yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void schema_yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* Accessor methods for yylval and yylloc */

/* %if-bison-bridge */

YYSTYPE * schema_yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void schema_yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *schema_yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void schema_yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* %endif */

/* User-visible API */

/* schema_yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int schema_yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) schema_yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* schema_yylex_init_extra has the same functionality as schema_yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to schema_yyalloc in
 * the yyextra field.
 */

int schema_yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    schema_yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) schema_yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    schema_yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from schema_yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * schema_yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* schema_yylex_destroy is for both reentrant and non-reentrant scanners. */
int schema_yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		schema_yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		schema_yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	schema_yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        schema_yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * schema_yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

/* %if-reentrant */
    /* Destroy the main struct (reentrant only). */
    schema_yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *schema_yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return (void *) malloc( size );
}

void *schema_yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void schema_yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see schema_yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 196 "/home/ncbi/devel/ncbi-vdb/libs/schema/schema-lex.l"



#include <klib/text.h>

void
SchemaScan_yylex_init ( SchemaScanBlock* sb, const char *str )
{
    schema_yylex_init ( & sb -> scanner );
    sb -> buffer = schema_yy_scan_string ( ( yyconst char * ) str, sb -> scanner );
    sb -> whitespace = NULL;
    ( ( struct yyguts_t * ) sb -> scanner ) -> yyextra_r = sb; /* back pointer to the scan block, not touched by flex */
}

void
SchemaScan_yylex_destroy ( SchemaScanBlock* sb )
{
    schema_yy_delete_buffer ( sb -> buffer, sb -> scanner );
    if ( sb -> scanner )
    {
        schema_yylex_destroy ( sb -> scanner );
    }
    sb -> scanner = NULL;
    sb -> buffer = NULL;
    free ( sb -> whitespace );
}

void
SchemaScan_set_debug ( SchemaScanBlock* sb, int on )
{
    schema_yyset_debug ( on ? 1 : 0, sb->scanner );
}

enum yytokentype
SchemaScan_yylex ( YYSTYPE *lvalp, YYLTYPE *llocp, SchemaScanBlock* sb )
{
    enum yytokentype ret = ( enum yytokentype ) schema_yylex ( lvalp, llocp, sb -> scanner );
    lvalp -> type       = ret;
    lvalp -> value      = ( ( struct yyguts_t * ) sb -> scanner ) -> yytext_r;
    lvalp -> value_len  = ( ( struct yyguts_t * ) sb -> scanner ) -> yyleng_r;
    lvalp -> leading_ws = sb -> whitespace; /* will be freed by the new owner */
    lvalp -> subtree = NULL;

    sb -> whitespace = NULL;

    return ret;
}

void
AddWhitespace ( SchemaScanBlock* p_sb, const char* p_ws, size_t p_length )
{
    if ( p_sb -> whitespace == NULL )
    {
        p_sb -> whitespace = malloc ( p_length + 1 );
        if ( p_sb -> whitespace != NULL )
        {
            string_copy ( p_sb -> whitespace, p_length + 1, p_ws, p_length ); /* will NUL-terminate */
        }
    }
    else
    {
        size_t old_size = string_size ( p_sb -> whitespace );
        size_t new_size = old_size + p_length + 1;
        p_sb -> whitespace = realloc ( p_sb -> whitespace, new_size );
        if ( p_sb -> whitespace != NULL )
        {
            string_copy ( p_sb -> whitespace + old_size, p_length + 1, p_ws, p_length ); /* will NUL-terminate */
        }
    }
}

