# ===========================================================================
#
#                            PUBLIC DOMAIN NOTICE
#               National Center for Biotechnology Information
#
#  This software/database is a "United States Government Work" under the
#  terms of the United States Copyright Act.  It was written as part of
#  the author's official duties as a United States Government employee and
#  thus cannot be copyrighted.  This software/database is freely available
#  to the public for use. The National Library of Medicine and the U.S.
#  Government have not placed any restriction on its use or reproduction.
#
#  Although all reasonable efforts have been taken to ensure the accuracy
#  and reliability of the software and data, the NLM and the U.S.
#  Government do not and cannot warrant the performance or results that
#  may be obtained by using this software or data. The NLM and the U.S.
#  Government disclaim all warranties, express or implied, including
#  warranties of performance, merchantability or fitness for any particular
#  purpose.
#
#  Please cite the author in any work or product based on this material.
#
# ===========================================================================

# defines globally available make targets:
#   makedirs
#   build
#   clean
#   test/check
#

#-------------------------------------------------------------------------------
# makedirs - create all required output directories
#
makedirs:
	@ mkdir -p $(TARGDIR)/obj/$(MODULE) $(LIBDIR) $(BINDIR) $(TEST_BINDIR)

.PHONY: makedirs

#-------------------------------------------------------------------------------
# build
#
SUBDIRS_BUILD ?= $(addsuffix _build,$(SUBDIRS))

$(SUBDIRS_BUILD):
	@ $(MAKE) -C $(subst _build,,$@) build

build: makedirs $(SUBDIRS_BUILD)

.PHONY: build $(SUBDIRS_BUILD)

#-------------------------------------------------------------------------------
# clean
#
stdclean:
	@ -rm -rf $(OBJDIR)

SUBDIRS_CLEAN ?= $(addsuffix _clean,$(SUBDIRS))

clean: stdclean $(SUBDIRS_CLEAN)

$(SUBDIRS_CLEAN):
	@ $(MAKE) --no-print-directory -s -C $(subst _clean,,$@) clean

.PHONY: clean stdclean $(SUBDIRS_CLEAN)

#-------------------------------------------------------------------------------
# test, check
#
# If a 'test' subdirectory exists, 'make test' in it. Do not list 'test' in SUBDIRS

SUBDIRS_TEST ?= $(addsuffix _test,$(SUBDIRS))

$(SUBDIRS_TEST):
	@ $(MAKE) -s -C $(subst _test,,$@) test

test: build $(SUBDIRS_TEST) own_test

own_test:
	if [ -d test ] ; then $(MAKE) -C test; fi

check: test

.PHONY: test $(SUBDIRS_TEST)

#-------------------------------------------------------------------------------
# help
#
stdhelp:
	@echo "Supported targets:"
	@echo "    help     - list targets"
	@echo "    build    - build"
	@echo "    clean    - remove build outputs"
	@echo "    test     - run tests (same as check)"
	@echo "    check    - run tests (same as test)"
	@echo "    config   - display configuration"

help: stdhelp

.phony: help stdhelp

#-------------------------------------------------------------------------------
# config
#
config:
	@ echo "  current build is $(BUILD)"
	@ echo "  output target directory is '$(TARGDIR)'"
	@ echo

.phony: config

#-------------------------------------------------------------------------------
# install
#
install: build

SUBDIRS_INST ?= $(addsuffix _inst,$(SUBDIRS))

$(SUBDIRS_INST):
	@ $(MAKE) -s -C $(subst _inst,,$@) subinstall

subinstall: $(SUBDIRS_INST)

.PHONY: install subinstall $(SUBDIRS_INST)

#-------------------------------------------------------------------------------
# guts: build system developer's target: show popular variables
guts:
	@echo "OUTDIR=$(OUTDIR)"
	@echo "TARGDIR=$(TARGDIR)"
	@echo "BINDIR=$(BINDIR)"
	@echo "TEST_BINDIR=$(TEST_BINDIR)"
	@echo "LIBDIR=$(LIBDIR)"
	@echo "SRCDIR=$(SRCDIR)"
	@echo "OBJDIR=$(OBJDIR)"
	@echo "SUBDIRS=$(SUBDIRS)"

.phony: guts

